version: '3.8'

services:
  database:
    image: postgres:16
    container_name: horsetrust-backend-database-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - horse-net
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring:
    image: ${BACKEND_IMAGE}
    container_name: horsetrust-backend-spring-1
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_PROFILE: ${SPRING_PROFILE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      # Explicitly Enabling Swagger in Prod Profile
      SPRINGDOC_SWAGGER_UI_ENABLED: ${SPRINGDOC_SWAGGER_UI_ENABLED}
      SPRINGDOC_API_DOCS_ENABLED: ${SPRINGDOC_API_DOCS_ENABLED}
      SPRINGDOC_API_DOCS_PATH: ${SPRINGDOC_API_DOCS_PATH}
      SPRINGDOC_SWAGGER_UI_CONFIG_URL: ${SPRINGDOC_SWAGGER_UI_CONFIG_URL}
      SPRINGDOC_SWAGGER_UI_URL: ${SPRINGDOC_SWAGGER_UI_URL}
      SERVER_FORWARD_HEADERS_STRATEGY: ${SERVER_FORWARD_HEADERS_STRATEGY}

      SECRET_KEY: ${SECRET_KEY}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      MAIL_ENABLED: ${MAIL_ENABLED}
      MAIL_FROM: ${MAIL_FROM}
      RESET_PASSWORD_BASE_URL: ${RESET_PASSWORD_BASE_URL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH}
      MAIL_SMTP_STARTTLS_ENABLE: ${MAIL_SMTP_STARTTLS_ENABLE}
      EMAIL_VERIFICATION_CODE_TTL_MINUTES: ${EMAIL_VERIFICATION_CODE_TTL_MINUTES}
      SERVER_PORT: 8090
    ports:
      - "8070:8090"
    networks:
      - horse-net
    restart: always

volumes:
  db_data:
    name: horsetrust_db_data

networks:
  horse-net:
    driver: bridge
